stages:
    - build

build-1_34:
    stage: build
    image: rust:1.34-slim
    dependencies: []
    script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo doc --verbose

build-stable:
    stage: build
    image: rust:latest
    dependencies: []
    script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo doc --verbose

build-beta:
    stage: build
    image: rust:latest
    dependencies: []
    before_script:
        - rustup default beta
    script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo doc --verbose

build-nightly:
    stage: build
    image: rust:latest
    dependencies: []
    before_script:
        - rustup default nightly
    script:
        - cargo generate-lockfile -Z minimal-versions
        - cargo build --verbose --locked
        - cargo test --verbose --locked
        - cargo doc --verbose --locked
